ExternalProject_Add(eigen
    URL ${eigen_url}
    URL_MD5 ${eigen_md5}
    DOWNLOAD_NAME ${eigen_dlname}
    ${COMMON_EP_ARGS}
    ${COMMON_CMAKE_EP_ARGS}
    CMAKE_ARGS
        ${COMMON_CMAKE_ARGS}
)

ExternalProject_Add_Step(
  eigen CopyLicense
  COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/src/eigen/COPYING.BSD ${LICENSE_DIR}/eigen/COPYING.BSD
  COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/src/eigen/COPYING.GPL ${LICENSE_DIR}/eigen/COPYING.GPL
  COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/src/eigen/COPYING.LGPL ${LICENSE_DIR}/eigen/COPYING.LGPL
  COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/src/eigen/COPYING.MINPACK ${LICENSE_DIR}/eigen/COPYING.MINPACK
  COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/src/eigen/COPYING.MPL2 ${LICENSE_DIR}/eigen/COPYING.MPL2
  COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/src/eigen/COPYING.README ${LICENSE_DIR}/eigen/COPYING.README
  DEPENDEES install
)